// <auto-generated />
using FourYearClassPlanningTool.Models.Users;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FourYearClassPlanningTool.Migrations.Users
{
    [DbContext(typeof(UsersContext))]
    [Migration("20210429154426_Modifications")]
    partial class Modifications
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourseSchedule", b =>
                {
                    b.Property<string>("CoursesCourseID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ScheduleID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CoursesCourseID", "ScheduleID");

                    b.HasIndex("ScheduleID");

                    b.ToTable("CourseSchedule");
                });

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.Property<string>("CompletedCoursesCourseID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsersUserID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CompletedCoursesCourseID", "UsersUserID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("CourseUser");
                });

            modelBuilder.Entity("FourYearClassPlanningTool.Models.Users.Entities.Admin", b =>
                {
                    b.Property<string>("AdminID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("FourYearClassPlanningTool.Models.Users.Entities.Course", b =>
                {
                    b.Property<string>("CourseID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SemesterOffered")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("FourYearClassPlanningTool.Models.Users.Entities.Schedule", b =>
                {
                    b.Property<string>("ScheduleID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Semester")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScheduleID");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("FourYearClassPlanningTool.Models.Users.Entities.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ScheduleUser", b =>
                {
                    b.Property<string>("SchedulesScheduleID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsersUserID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SchedulesScheduleID", "UsersUserID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("ScheduleUser");
                });

            modelBuilder.Entity("CourseSchedule", b =>
                {
                    b.HasOne("FourYearClassPlanningTool.Models.Users.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesCourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FourYearClassPlanningTool.Models.Users.Entities.Schedule", null)
                        .WithMany()
                        .HasForeignKey("ScheduleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.HasOne("FourYearClassPlanningTool.Models.Users.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CompletedCoursesCourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FourYearClassPlanningTool.Models.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleUser", b =>
                {
                    b.HasOne("FourYearClassPlanningTool.Models.Users.Entities.Schedule", null)
                        .WithMany()
                        .HasForeignKey("SchedulesScheduleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FourYearClassPlanningTool.Models.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
